'use client'

import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import {
  Mic, Sparkles, Download, Trash2, ChevronDown, ChevronRight,
  ArrowRight, CheckSquare, RefreshCw, Check,
  Plus, Loader2, X, AlertTriangle,
} from 'lucide-react'
import { teamApi, type MeetingSummary, type MeetingAnalysis, type MeetingActionItem, type MeetingContentIdea } from '@/lib/api'
import { PageHeader } from '@/components/shared/PageHeader'
import { EmptyState } from '@/components/shared/EmptyState'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'

// ── Sentiment badge ───────────────────────────────────────────

const SENTIMENT_STYLES: Record<string, string> = {
  POSITIVE: 'bg-green-500/15 text-green-400 border-green-500/30',
  NEUTRAL:  'bg-slate-500/15 text-slate-400 border-slate-500/30',
  MIXED:    'bg-amber-500/15 text-amber-400 border-amber-500/30',
  NEGATIVE: 'bg-red-500/15 text-red-400 border-red-500/30',
}

const PRIORITY_STYLES: Record<string, string> = {
  HIGH:   'bg-red-500/15 text-red-400',
  MEDIUM: 'bg-amber-500/15 text-amber-400',
  LOW:    'bg-slate-500/15 text-slate-400',
}

// ── Download helpers ──────────────────────────────────────────

function buildTxtContent(title: string, analysis: MeetingAnalysis): string {
  return [
    `MEETING INTELLIGENCE REPORT`,
    `═══════════════════════════════════════`,
    `Title: ${title}`,
    `Date: ${analysis.date}`,
    `Duration: ${analysis.duration}`,
    `Participants: ${analysis.participants.join(', ')}`,
    `Sentiment: ${analysis.sentiment}`,
    ``,
    `EXECUTIVE SUMMARY`,
    `─────────────────`,
    analysis.executiveSummary,
    ``,
    `KEY DECISIONS`,
    `─────────────`,
    ...(analysis.keyDecisions.map((d, i) => `${i + 1}. ${d}`)),
    ``,
    `ACTION ITEMS`,
    `────────────`,
    ...(analysis.actionItems.map((a, i) =>
      `${i + 1}. [${a.priority}] ${a.task}\n   Owner: ${a.owner} | Deadline: ${a.deadline}`
    )),
    ``,
    `CONTENT IDEAS`,
    `─────────────`,
    ...(analysis.contentIdeas.map((c, i) =>
      `${i + 1}. ${c.title}\n   Platform: ${c.platform} | Format: ${c.format}\n   Hook: ${c.hook}`
    )),
    ``,
    `FOLLOW-UP QUESTIONS`,
    `───────────────────`,
    ...(analysis.followUpQuestions.map((q, i) => `${i + 1}. ${q}`)),
    ``,
    `NEXT MEETING AGENDA`,
    `───────────────────`,
    ...(analysis.nextMeetingAgenda.map((a, i) => `${i + 1}. ${a}`)),
    ``,
    `───────────────────────────────────────`,
    `Generated by SocialPulse AI Meeting Intelligence`,
  ].join('\n')
}

function downloadTxt(title: string, analysis: MeetingAnalysis) {
  const content = buildTxtContent(title, analysis)
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `meeting-${title.toLowerCase().replace(/\s+/g, '-')}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function downloadJson(title: string, analysis: MeetingAnalysis) {
  const blob = new Blob([JSON.stringify({ title, ...analysis }, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `meeting-${title.toLowerCase().replace(/\s+/g, '-')}.json`
  a.click()
  URL.revokeObjectURL(url)
}

function buildHtmlContent(title: string, analysis: MeetingAnalysis): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>${title} — Meeting Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; background: #fafafa; }
    h1 { font-size: 1.5rem; color: #111; margin-bottom: 4px; }
    .meta { color: #666; font-size: 0.875rem; margin-bottom: 32px; }
    h2 { font-size: 1rem; font-weight: 700; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-top: 28px; }
    p { line-height: 1.6; }
    ul { padding-left: 20px; }
    li { margin-bottom: 6px; line-height: 1.5; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; margin-right: 4px; }
    .high { background: #fee2e2; color: #dc2626; }
    .medium { background: #fef3c7; color: #d97706; }
    .low { background: #f1f5f9; color: #64748b; }
    .action { background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; margin-bottom: 8px; }
    .idea { background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; margin-bottom: 8px; }
    .hook { color: #6366f1; font-style: italic; font-size: 0.875rem; margin-top: 4px; }
    footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 16px; color: #9ca3af; font-size: 0.75rem; text-align: center; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">📅 ${analysis.date} &nbsp;|&nbsp; ⏱ ${analysis.duration} &nbsp;|&nbsp; 👥 ${analysis.participants.join(', ')} &nbsp;|&nbsp; Sentiment: ${analysis.sentiment}</p>

  <h2>Executive Summary</h2>
  <p>${analysis.executiveSummary}</p>

  <h2>Key Decisions</h2>
  <ul>${analysis.keyDecisions.map((d) => `<li>${d}</li>`).join('')}</ul>

  <h2>Action Items</h2>
  ${analysis.actionItems.map((a) => `
    <div class="action">
      <span class="badge ${a.priority.toLowerCase()}">${a.priority}</span>
      <strong>${a.task}</strong><br/>
      <small>Owner: ${a.owner} &nbsp;·&nbsp; Deadline: ${a.deadline}</small>
    </div>
  `).join('')}

  <h2>Content Ideas</h2>
  ${analysis.contentIdeas.map((c) => `
    <div class="idea">
      <strong>${c.title}</strong>
      <small> — ${c.platform} · ${c.format}</small>
      <p class="hook">"${c.hook}"</p>
    </div>
  `).join('')}

  <h2>Follow-up Questions</h2>
  <ul>${analysis.followUpQuestions.map((q) => `<li>${q}</li>`).join('')}</ul>

  <h2>Next Meeting Agenda</h2>
  <ul>${analysis.nextMeetingAgenda.map((a) => `<li>${a}</li>`).join('')}</ul>

  <footer>Generated by SocialPulse AI Meeting Intelligence · ${new Date().toLocaleDateString()}</footer>
</body>
</html>`
}

function downloadHtml(title: string, analysis: MeetingAnalysis) {
  const blob = new Blob([buildHtmlContent(title, analysis)], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `meeting-${title.toLowerCase().replace(/\s+/g, '-')}.html`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Analysis result card ──────────────────────────────────────

function AnalysisCard({
  summary,
  onDelete,
}: {
  summary: MeetingSummary
  onDelete: () => void
}) {
  const [expanded, setExpanded] = useState(false)
  const { analysis } = summary

  if (!analysis) return null

  return (
    <Card className="overflow-hidden">
      {/* Header */}
      <CardHeader
        className="cursor-pointer p-4 pb-3 hover:bg-surface-2 transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        <div className="flex items-start gap-3">
          <div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[var(--color-accent-light)] text-[var(--color-accent)]">
            <Mic className="h-4 w-4" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="font-semibold text-sm text-[var(--color-text)] leading-tight">
              {summary.title}
            </p>
            <div className="mt-1 flex items-center gap-2 flex-wrap">
              <p className="text-[10px] text-[var(--color-text-4)]">
                {new Date(summary.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
                {' · '}{analysis.duration}
                {' · '}{analysis.participants.length} participants
              </p>
              <span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${SENTIMENT_STYLES[analysis.sentiment] ?? ''}`}>
                {analysis.sentiment}
              </span>
            </div>
          </div>
          <div className="flex items-center gap-1 shrink-0">
            {expanded ? <ChevronDown className="h-4 w-4 text-[var(--color-text-4)]" /> : <ChevronRight className="h-4 w-4 text-[var(--color-text-4)]" />}
          </div>
        </div>
      </CardHeader>

      {expanded && (
        <CardContent className="p-4 pt-0">
          {/* Summary */}
          <div className="rounded-lg bg-surface-2 border border-brand-border p-3 mb-4">
            <p className="text-xs font-semibold text-[var(--color-text-3)] uppercase tracking-wide mb-1">Executive Summary</p>
            <p className="text-sm text-[var(--color-text-2)] leading-relaxed">{analysis.executiveSummary}</p>
          </div>

          {/* Key decisions */}
          {analysis.keyDecisions.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-[var(--color-text-3)] uppercase tracking-wide mb-2">Key Decisions</p>
              <ul className="space-y-1.5">
                {analysis.keyDecisions.map((d, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-[var(--color-text-2)]">
                    <CheckSquare className="h-3.5 w-3.5 mt-0.5 shrink-0 text-green-400" />
                    {d}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Action items */}
          {analysis.actionItems.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-[var(--color-text-3)] uppercase tracking-wide mb-2">
                Action Items ({analysis.actionItems.length})
              </p>
              <div className="space-y-2">
                {analysis.actionItems.map((a, i) => (
                  <div key={i} className="flex items-start gap-2.5 rounded-lg border border-brand-border bg-surface p-3">
                    <span className={`mt-0.5 rounded px-1.5 py-0.5 text-[10px] font-bold shrink-0 ${PRIORITY_STYLES[a.priority] ?? ''}`}>
                      {a.priority}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-[var(--color-text)]">{a.task}</p>
                      <p className="text-[11px] text-[var(--color-text-4)] mt-0.5">
                        {a.owner} · {a.deadline}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Content ideas */}
          {analysis.contentIdeas.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-[var(--color-text-3)] uppercase tracking-wide mb-2">
                Content Ideas ({analysis.contentIdeas.length})
              </p>
              <div className="space-y-2">
                {analysis.contentIdeas.map((c, i) => (
                  <div key={i} className="rounded-lg border border-brand-border bg-surface-2 p-3">
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-medium text-[var(--color-text)] leading-tight">{c.title}</p>
                      <div className="flex items-center gap-1 shrink-0">
                        <Badge variant="outline" className="text-[10px] px-1.5 py-0">{c.platform}</Badge>
                        <Badge variant="secondary" className="text-[10px] px-1.5 py-0">{c.format}</Badge>
                      </div>
                    </div>
                    <p className="mt-1.5 text-xs text-[var(--color-accent)] italic">"{c.hook}"</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Agenda */}
          {analysis.nextMeetingAgenda.length > 0 && (
            <div className="mb-4">
              <p className="text-xs font-semibold text-[var(--color-text-3)] uppercase tracking-wide mb-2">Next Meeting Agenda</p>
              <ul className="space-y-1">
                {analysis.nextMeetingAgenda.map((a, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-[var(--color-text-2)]">
                    <ArrowRight className="h-3 w-3 shrink-0 text-[var(--color-text-4)]" />
                    {a}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Tags */}
          {summary.tags.length > 0 && (
            <div className="flex flex-wrap gap-1 mb-4">
              {summary.tags.map((tag) => (
                <span
                  key={tag}
                  className="rounded-full bg-[var(--color-accent)]/10 px-2 py-0.5 text-[10px] text-[var(--color-accent)]"
                >
                  #{tag}
                </span>
              ))}
            </div>
          )}

          {/* Download + Delete */}
          <div className="flex items-center gap-2 pt-2 border-t border-brand-border">
            <span className="text-xs text-[var(--color-text-4)] flex items-center gap-1 mr-1">
              <Download className="h-3 w-3" /> Download:
            </span>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={() => downloadTxt(summary.title, analysis)}
            >
              TXT
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={() => downloadHtml(summary.title, analysis)}
            >
              HTML
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={() => downloadJson(summary.title, analysis)}
            >
              JSON
            </Button>
            <div className="ml-auto">
              <Button
                size="sm"
                variant="ghost"
                className="h-7 text-xs text-red-400 hover:text-red-500"
                onClick={onDelete}
              >
                <Trash2 className="h-3 w-3 mr-1" /> Delete
              </Button>
            </div>
          </div>
        </CardContent>
      )}
    </Card>
  )
}

// ── Analyze form ──────────────────────────────────────────────

function AnalyzeForm({ onClose }: { onClose: () => void }) {
  const qc = useQueryClient()
  const [title, setTitle] = useState('')
  const [transcript, setTranscript] = useState('')
  const [participants, setParticipants] = useState('')
  const [duration, setDuration] = useState('')
  const [result, setResult] = useState<{ id: string; title: string; analysis: MeetingAnalysis } | null>(null)

  const analyzeMutation = useMutation({
    mutationFn: () =>
      teamApi.analyzeMeeting({
        title: title || undefined,
        transcript,
        participants: participants || undefined,
        duration: duration || undefined,
      }),
    onSuccess: (data) => {
      setResult(data)
      void qc.invalidateQueries({ queryKey: ['team', 'meetings'] })
    },
  })

  if (result) {
    // Show quick summary of what was just analyzed
    return (
      <Card className="border-green-500/40">
        <CardContent className="p-5">
          <div className="flex items-start gap-3 mb-4">
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-green-500/15 text-green-400">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold text-[var(--color-text)]">Analysis complete!</p>
              <p className="text-xs text-[var(--color-text-4)] mt-0.5">
                {result.analysis.actionItems.length} action items · {result.analysis.contentIdeas.length} content ideas
              </p>
            </div>
          </div>
          <p className="text-sm text-[var(--color-text-2)] rounded-lg bg-surface-2 border border-brand-border p-3 leading-relaxed">
            {result.analysis.executiveSummary}
          </p>
          <div className="mt-4 flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={() => downloadTxt(result.title, result.analysis)}
            >
              <Download className="h-3 w-3 mr-1" /> TXT
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={() => downloadHtml(result.title, result.analysis)}
            >
              <Download className="h-3 w-3 mr-1" /> HTML
            </Button>
            <Button
              size="sm"
              className="h-7 text-xs ml-auto gap-1"
              onClick={onClose}
            >
              <Check className="h-3 w-3" /> Done
            </Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="border-[var(--color-accent)]/40">
      <CardContent className="p-5">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Mic className="h-4 w-4 text-[var(--color-accent)]" />
            <p className="font-semibold text-sm text-[var(--color-text)]">Analyze Meeting</p>
          </div>
          <Button size="icon" variant="ghost" onClick={onClose} className="h-7 w-7">
            <X className="h-3.5 w-3.5" />
          </Button>
        </div>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3 mb-3">
          <div className="sm:col-span-1">
            <label className="mb-1.5 block text-xs font-medium text-[var(--color-text-3)]">
              Meeting Title
            </label>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Q2 Content Planning"
              className="text-sm"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-xs font-medium text-[var(--color-text-3)]">
              Duration
            </label>
            <Input
              value={duration}
              onChange={(e) => setDuration(e.target.value)}
              placeholder="e.g. 45 minutes"
              className="text-sm"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-xs font-medium text-[var(--color-text-3)]">
              Participants (comma-separated)
            </label>
            <Input
              value={participants}
              onChange={(e) => setParticipants(e.target.value)}
              placeholder="Mani, Priya, Rahul"
              className="text-sm"
            />
          </div>
        </div>

        <div className="mb-4">
          <label className="mb-1.5 block text-xs font-medium text-[var(--color-text-3)]">
            Meeting Transcript / Notes *
          </label>
          <Textarea
            value={transcript}
            onChange={(e) => setTranscript(e.target.value)}
            placeholder="Paste your meeting transcript, notes, or key points here. The AI will extract action items, decisions, content ideas, and generate a structured summary.

Example:
Mani: We need to ramp up our Instagram presence this quarter...
Priya: I think we should focus on Reels, the engagement is much higher...
Rahul: Let's set a target of 5 Reels per week..."
            rows={10}
            className="text-sm resize-none font-mono"
          />
          <p className="mt-1 text-[10px] text-[var(--color-text-4)]">
            Minimum 50 characters · Maximum 50,000 characters
          </p>
        </div>

        {analyzeMutation.isError && (
          <div className="mb-4 flex items-center gap-2 rounded-lg bg-red-500/10 border border-red-500/20 p-3 text-sm text-red-400">
            <AlertTriangle className="h-4 w-4 shrink-0" />
            Analysis failed. Please check your input and try again.
          </div>
        )}

        <Button
          onClick={() => analyzeMutation.mutate()}
          disabled={transcript.trim().length < 50 || analyzeMutation.isPending}
          className="w-full gap-2"
        >
          {analyzeMutation.isPending ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Analyzing with AI… (this takes 10–20 seconds)
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4" />
              Analyze Meeting
            </>
          )}
        </Button>
      </CardContent>
    </Card>
  )
}

// ── Page ──────────────────────────────────────────────────────

export function MeetingIntelligencePage() {
  const qc = useQueryClient()
  const [analyzing, setAnalyzing] = useState(false)

  const { data: meetings = [], isLoading, isFetching, refetch } = useQuery({
    queryKey: ['team', 'meetings'],
    queryFn: () => teamApi.listMeetings(),
    staleTime: 60_000,
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => teamApi.deleteMeeting(id),
    onSuccess: () => void qc.invalidateQueries({ queryKey: ['team', 'meetings'] }),
  })

  return (
    <>
      <PageHeader
        title="Meeting Intelligence"
        description="Paste any meeting transcript and AI extracts action items, decisions, content ideas, and a structured report."
        icon={<Mic className="h-5 w-5" />}
        actions={
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => refetch()}
              disabled={isFetching}
              className="h-8 w-8 p-0"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${isFetching ? 'animate-spin' : ''}`} />
            </Button>
            {!analyzing && (
              <Button
                size="sm"
                className="h-8 gap-1.5"
                onClick={() => setAnalyzing(true)}
              >
                <Plus className="h-3.5 w-3.5" />
                Analyze Meeting
              </Button>
            )}
          </div>
        }
      />

      {/* Analyze form */}
      {analyzing && (
        <div className="mt-6">
          <AnalyzeForm onClose={() => setAnalyzing(false)} />
        </div>
      )}

      {/* Loading skeleton */}
      {isLoading && (
        <div className="mt-6 space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="h-20 rounded-xl bg-surface-2 animate-pulse" />
          ))}
        </div>
      )}

      {/* Empty state */}
      {!isLoading && meetings.length === 0 && !analyzing && (
        <Card className="mt-6">
          <CardContent className="p-0">
            <EmptyState
              icon={<Mic className="h-12 w-12" />}
              heading="No meeting analyses yet"
              description="Paste a meeting transcript or notes and let AI extract action items, decisions, content ideas, and a structured report you can download."
              action={{ label: 'Analyze First Meeting', onClick: () => setAnalyzing(true) }}
            />
          </CardContent>
        </Card>
      )}

      {/* Meetings list */}
      {!isLoading && meetings.length > 0 && (
        <div className="mt-6 space-y-3">
          {meetings.map((meeting) => (
            <AnalysisCard
              key={meeting.id}
              summary={meeting}
              onDelete={() => deleteMutation.mutate(meeting.id)}
            />
          ))}
        </div>
      )}
    </>
  )
}
